config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  root 'pokemons#index'
  
  get 'pokemons/instructions', to: 'pokemons#instructions', as: 'pokemon_instructions'
  resources :pokemons, only: [:index, :show]
  resources :types, only: [:index, :show]
  
  get 'about', to: 'pages#about'
  get 'pokemons/type/:type', to: 'pokemons#index', as: 'type_pokemons'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
# app/models/pokemon.rb
class Pokemon < ApplicationRecord
    has_many :pokemon_types
    has_many :types, through: :pokemon_types
  
   # Validations
   validates :name, presence: true, uniqueness: true
   validates :number, presence: true, numericality: { only_integer: true, greater_than: 0 }
 end

app/models/pokemon_type.rb
class PokemonType < ApplicationRecord
  belongs_to :pokemon
  belongs_to :type

# Validations
validates :pokemon_id, presence: true
validates :type_id, presence: true
validates :pokemon_id, uniqueness: { scope: :type_id, message: "Pokemon can only have one specific type assigned once" }
end

app/models/type.rb
# app/models/type.rb
class Type < ApplicationRecord
    has_many :pokemon_types
    has_many :pokemons, through: :pokemon_types

    # Validations
    validates :name, presence: true, uniqueness: true
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
    @types = Type.all

    if params[:type].present? && params[:type] != 'All'
      @type = Type.find_by(name: params[:type])
      @pokemons = @type.pokemons
    else
      @pokemons = Pokemon.all
    end

    if params[:search].present?
      search_term = "#{params[:search].downcase}%"
      @pokemons = @pokemons.where('LOWER(species) LIKE ?', search_term)
    end

    if params[:sort].present?
      sort_order = params[:sort] == 'asc' ? 'ASC' : 'DESC'
      @pokemons = @pokemons.order("species COLLATE NOCASE #{sort_order}")
    end

    # Add pagination
    @pokemons = @pokemons.page(params[:page]).per(9)
  end

  def show
    @pokemon = Pokemon.find(params[:id])
  end

  def instructions
  end
end

app/controllers/types_controller.rb
# app/controllers/types_controller.rb
class TypesController < ApplicationController
  def index
    @types = Type.all
  end

  def show
    @type = Type.find(params[:id])
    @pokemons = @type.pokemons
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokemonHub</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1 class="text-center my-4">About Pokémon Hub</h1>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title">Welcome to Pokémon Hub!</h2>
          <p class="card-text">This website allows you to view and explore various Pokémon species. You can browse through different categories, view detailed information about each Pokémon, and more.</p>
          <p class="card-text">Here are some features of our website:</p>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Browse Pokémon by category</li>
            <li class="list-group-item">View detailed information about each Pokémon, including species, types, abilities, and more</li>
            <li class="list-group-item">Use the search functionality to quickly find your favorite Pokémon</li>
          </ul>
          <p class="card-text mt-3">We hope you enjoy using Pokémon Hub!</p>
          
          <!-- Image inclusion -->
          <img src="/assets/Screenshot 2024-07-03 111644-8ffcb1b469a33f832c2432cd785bce8d93f74b063fc8751c94be40ce337655d9.png" />

          <!-- Description of the dataset -->
          <h2 class="card-title mt-4">Our Dataset</h2>
          <p class="card-text">The Pokémon Hub fetches data from a comprehensive GraphQL API provided by <a href="https://graphqlpokemon.favware.tech/v8" target="_blank">Favware's GraphQL Pokémon API</a>. This API allows us to access detailed information about each Pokémon species, including their types, abilities, base stats, and more. By using this powerful API, we ensure that our users have access to the most accurate and up-to-date information about their favorite Pokémon.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pokemons/index.html.erb
<h1 class="text-center my-4">Pokémon--Hub</h1>
<div class="container mb-4">
  <div class="row justify-content-center">
    <div class="col-md-4">
      <%= form_with url: root_path, method: :get, local: true, class: 'd-flex' do |form| %>
        <%= hidden_field_tag :type, params[:type] if params[:type].present? %>
        <%= form.text_field :search, class: 'form-control me-2', placeholder: 'Search Pokémon...', style: 'width: 200px;' %>
        <%= form.submit 'Search', class: 'btn btn-outline-success' %>
      <% end %>
    </div>
    <div class="col-md-4">
      <%= form_with url: root_path, method: :get, local: true, class: 'd-flex align-items-center' do |form| %>
        <%= hidden_field_tag :type, params[:type] if params[:type].present? %>
        <%= form.label :sort, 'Sort by:', class: 'me-2 mb-0', style: 'margin-left: 10px;' %>
        <%= form.select :sort, [['Ascending', 'asc'], ['Descending', 'desc']], { include_blank: true }, class: 'form-select me-2', style: 'width: 150px;' %>
        <%= form.submit 'Sort', class: 'btn btn-outline-primary' %>
      <% end %>
    </div>
    <div class="col-md-4 d-flex justify-content-end align-items-center">
      <!-- Add pagination links -->
      <div class="pagination-links">
        <%= paginate @pokemons %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>Types</h2>
      <ul class="list-group">
        <li class="list-group-item <%= 'active' if params[:type].nil? || params[:type] == 'All' %>">
          <%= link_to 'All', pokemons_path %>
        </li>
        <% @types.each do |type| %>
          <li class="list-group-item <%= 'active' if @type && @type.name == type.name %>">
            <%= link_to type.name, pokemons_path(type: type.name) %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-9">
      <h2>Pokémon List</h2>
      <% if @type %>
        <h4 class="text-muted" style="font-size: 1rem;">Type: <%= @type.name %></h4>
      <% end %>
      <div class="row">
        <% @pokemons.each do |pokemon| %>
          <div class="col-md-4 mb-4">
            <div class="card">
              <%= link_to image_tag(pokemon.sprite, class: 'card-img-top'), pokemon_path(pokemon) %>
              <div class="card-body">
                <h5 class="card-title"><%= link_to pokemon.species, pokemon_path(pokemon) %></h5>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pokemons/instructions.html.erb
<div class="container">
  <h1 class="text-center my-4">Pokémon Details</h1>
  <p>This page shows the Pokémon details when you click on a Pokémon from the Pokémon list.</p>
</div>

app/views/pokemons/show.html.erb
<!-- app/views/pokemons/show.html.erb -->
<% if @pokemon %>
  <h1 class="text-center my-4"><%= @pokemon.species %> Details</h1>

  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h2>Categories</h2>
        <ul class="list-group">
          <% @pokemon.types.each do |type| %>
            <li class="list-group-item"><%= type.name %></li>
          <% end %>
        </ul>
      </div>
      <div class="col-md-9">
        <h2 class="text-center my-4"><%= @pokemon.species %> Details</h2>
        <div class="card mb-4">
          <div class="card-img-top text-center">
            <%= image_tag @pokemon.sprite, class: 'img-fluid', style: 'max-width: 100%; height: auto; width: auto; max-height: 400px;' %>
          </div>
          <div class="card-body">
            <h5 class="card-title text-center"><%= @pokemon.species %></h5>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><strong>Height:</strong> <%= @pokemon.height %> m</li>
              <li class="list-group-item"><strong>Weight:</strong> <%= @pokemon.weight %> kg</li>
              <li class="list-group-item"><strong>Ability:</strong> <%= @pokemon.abilities %></li>
              <li class="list-group-item"><strong>Types:</strong>
                <% @pokemon.types.each do |type| %>
                  <%= type.name %><br>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="container">
    <h1 class="text-center my-4">Pokémon Details</h1>
    <p>This page shows the Pokémon details when you click on a Pokémon from the Pokémon list.</p>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Pokémon Hub</a>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Show', pokemon_instructions_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/types/index.html.erb
<h1>Types#index</h1>
<p>Find me in app/views/types/index.html.erb</p>

app/views/types/show.html.erb
<h1>Types#show</h1>
<p>Find me in app/views/types/show.html.erb</p>